### ISSUE TITLE
Infernal Edges not marked as a Cave Area in Collectibles MapLayer

### ISSUE THREAD

**Issue by Brackleforth** [frontiernav/frontiernav-data#4]
In Cauldros, the cave "Infernal Edges" northeast of the nopon caravan does not have a highlighted display. Also, the other cave area locations in Cauldros may not actually have any collectables in them - needs to be double-checked.

**Comment by jahed** [comment]
Thanks for reporting.

There's probably a lot of other missing caves in the collectible view so I'll probably want to go through and mark them up correctly.

Collectible-wise though, the current caves on the map are enough to find the collectibles so it's not that important. I'll probably get round to it the next time I'm working on that part of the data.

Happy to take a pull request if someone figures out how it's done (add a MapMarker, MAP_LINK it to the CollectibleArea and link to to the Collectibles MapLayer). Though, it's not very intuitive at the moment.

**Comment by hex7cd** [comment]
Now I have something to do for this evening. Can't be too difficult.

**Comment by jahed** [comment]
The change will be picked up on the next version deploy. Closing the issue.
